---
- name: uninstallhttpd webserver
  hosts: all
  become: yes
  tasks:
  - name: uninstall apache packages
    yum:
      name: httpd
      state: absent
  - name: close port
    firewalld:
      service: http
      permanent: yes
      state: disabled
  - name: Delete a file
    file:
      path: /var/www/html/index.html
      state: absent
